In [184]:
import numpy as np
import pandas as pd
from pathlib import Path

In [185]:
# d126 = pd.read_csv('/Users/manton/Documents/Code/Trading/DATA/USOILm_M5_202601012300_202604060000.csv')

# d126

In [186]:
# def prep_data(file_path):
#     file_ = pd.read_csv(file_path, sep='\t')
#     # <DATE>	<TIME>	<OPEN>	<HIGH>	<LOW>	<CLOSE>	<TICKVOL>	<VOL>	<SPREAD>
#     file_.columns = [col.replace('<', '').replace('>', '').lower() for col in file_.columns]
#     file_['datetime'] = pd.to_datetime(file_['date'] + ' ' + file_['time'])
#     file_.set_index('datetime', inplace=True)
#     file_.drop(columns=['date', 'time'], inplace=True)
#     file_ = file_

#     return file_

In [187]:
# d126 = pd.read_csv('/Users/manton/Documents/Code/Trading/DATA/USOILm_M5_202601012300_202604060000.csv', index_col=0)
# d425 = pd.read_csv('/Users/manton/Documents/Code/Trading/DATA/USOILm_M5_202510010000_202512310000.csv', index_col=0)
# d325 = pd.read_csv('/Users/manton/Documents/Code/Trading/DATA/USOILm_M5_202507010000_202509300000.csv', index_col=0)
# d225 = pd.read_csv('/Users/manton/Documents/Code/Trading/DATA/USOILm_M5_202504010000_202506300000.csv', index_col=0)
# d125 = pd.read_csv('/Users/manton/Documents/Code/Trading/DATA/USOILm_M5_202501012310_202503310000.csv', index_col=0)
# d424 = pd.read_csv('/Users/manton/Documents/Code/Trading/DATA/USOILm_M5_202410251230_202412310000.csv', index_col=0)
old_df = pd.read_csv('/Users/manton/Documents/Code/Trading/DATA/USOIL.csv', index_col=0)

data_dir = Path("/Users/manton/Documents/Code/Trading/DATA")
latest_file = sorted(data_dir.glob("USOILm_M*.csv"))[-1]
print("Latest file:", latest_file)
recent_df = pd.read_csv(latest_file, index_col=0)

df = pd.concat([old_df,recent_df], axis=0)

df

Latest file: /Users/manton/Documents/Code/Trading/DATA/USOILm_M5_202606082030_202606090550.csv

Empty DataFrame
Columns: []
Index: [2024.10.25	12:30:00	70.723	70.788	70.718	70.756	199	0	17, 2024.10.25	12:35:00	70.755	70.803	70.709	70.787	239	0	17, 2024.10.25	12:40:00	70.791	70.956	70.789	70.946	302	0	17, 2024.10.25	12:45:00	70.945	70.961	70.854	70.937	232	0	17, 2024.10.25	12:50:00	70.939	70.981	70.919	70.947	149	0	17, 2024.10.25	12:55:00	70.948	71.068	70.948	71.001	304	0	17, 2024.10.25	13:00:00	70.998	71.070	70.824	70.875	556	0	17, 2024.10.25	13:05:00	70.878	70.991	70.850	70.929	376	0	17, 2024.10.25	13:10:00	70.926	71.027	70.844	70.904	320	0	17, 2024.10.25	13:15:00	70.898	71.052	70.893	71.048	342	0	17, 2024.10.25	13:20:00	71.052	71.056	70.964	71.004	246	0	17, 2024.10.25	13:25:00	71.010	71.197	71.010	71.152	306	0	17, 2024.10.25	13:30:00	71.154	71.272	70.972	71.033	528	0	17, 2024.10.25	13:35:00	71.042	71.118	70.914	71.067	393	0	17, 2024.10.25	13:40:00	71.056	71.208	71.056	71.133	330	0	17, 2024.10.25	13:45:00	71.136	71.253	71.113	71.230	391	0	17, 2024.10.25	13:50:00	71.233	71.244	71.081	71.105	315	0	17, 2024.10.25	13:55:00	71.105	71.124	71.043	71.102	269	0	17, 2024.10.25	14:00:00	71.106	71.155	71.055	71.113	316	0	17, 2024.10.25	14:05:00	71.112	71.187	71.090	71.171	272	0	17, 2024.10.25	14:10:00	71.166	71.185	70.957	71.007	414	0	17, 2024.10.25	14:15:00	71.013	71.057	70.959	70.990	310	0	17, 2024.10.25	14:20:00	70.994	71.115	70.954	70.983	367	0	17, 2024.10.25	14:25:00	70.977	71.114	70.945	71.071	310	0	17, 2024.10.25	14:30:00	71.076	71.144	70.994	71.071	310	0	17, 2024.10.25	14:35:00	71.075	71.113	71.034	71.094	244	0	17, 2024.10.25	14:40:00	71.094	71.120	71.021	71.034	264	0	17, 2024.10.25	14:45:00	71.039	71.062	70.924	70.993	321	0	17, 2024.10.25	14:50:00	70.995	71.034	70.800	70.874	353	0	17, 2024.10.25	14:55:00	70.878	70.883	70.743	70.838	391	0	17, 2024.10.25	15:00:00	70.840	70.873	70.726	70.789	404	0	17, 2024.10.25	15:05:00	70.790	70.867	70.702	70.800	370	0	17, 2024.10.25	15:10:00	70.795	70.840	70.737	70.793	369	0	17, 2024.10.25	15:15:00	70.798	70.985	70.755	70.978	329	0	17, 2024.10.25	15:20:00	70.988	71.169	70.927	71.050	461	0	17, 2024.10.25	15:25:00	71.054	71.793	71.038	71.524	884	0	17, 2024.10.25	15:30:00	71.534	71.629	71.369	71.535	720	0	17, 2024.10.25	15:35:00	71.519	71.755	71.514	71.696	580	0	17, 2024.10.25	15:40:00	71.693	71.778	71.581	71.627	579	0	17, 2024.10.25	15:45:00	71.630	71.737	71.507	71.555	446	0	17, 2024.10.25	15:50:00	71.560	71.654	71.507	71.514	489	0	17, 2024.10.25	15:55:00	71.509	71.547	71.423	71.500	384	0	17, 2024.10.25	16:00:00	71.507	71.527	71.355	71.428	398	0	17, 2024.10.25	16:05:00	71.430	71.434	71.309	71.384	410	0	17, 2024.10.25	16:10:00	71.391	71.399	71.015	71.021	614	0	17, 2024.10.25	16:15:00	71.018	71.255	71.014	71.226	420	0	17, 2024.10.25	16:20:00	71.228	71.349	71.163	71.341	333	0	17, 2024.10.25	16:25:00	71.344	71.456	71.314	71.414	308	0	17, 2024.10.25	16:30:00	71.421	71.483	71.322	71.452	249	0	17, 2024.10.25	16:35:00	71.451	71.567	71.448	71.495	233	0	17, 2024.10.25	16:40:00	71.496	71.539	71.449	71.477	239	0	17, 2024.10.25	16:45:00	71.477	71.523	71.459	71.498	205	0	17, 2024.10.25	16:50:00	71.505	71.625	71.500	71.570	202	0	17, 2024.10.25	16:55:00	71.572	71.573	71.480	71.565	248	0	17, 2024.10.25	17:00:00	71.567	71.614	71.448	71.585	282	0	17, 2024.10.25	17:05:00	71.590	71.608	71.526	71.550	214	0	17, 2024.10.25	17:10:00	71.549	71.575	71.494	71.524	196	0	17, 2024.10.25	17:15:00	71.521	71.577	71.469	71.548	230	0	17, 2024.10.25	17:20:00	71.540	71.619	71.540	71.544	175	0	17, 2024.10.25	17:25:00	71.545	71.603	71.527	71.543	143	0	17, 2024.10.25	17:30:00	71.543	71.582	71.453	71.481	233	0	17, 2024.10.25	17:35:00	71.482	71.482	71.346	71.439	230	0	17, 2024.10.25	17:40:00	71.442	71.518	71.442	71.513	179	0	17, 2024.10.25	17:45:00	71.508	71.547	71.474	71.489	167	0	17, 2024.10.25	17:50:00	71.488	71.538	71.456	71.485	177	0	17, 2024.10.25	17:55:00	71.488	71.529	71.437	71.520	187	0	17, 2024.10.25	18:00:00	71.515	71.521	71.432	71.449	231	0	17, 2024.10.25	18:05:00	71.446	71.461	71.335	71.370	206	0	17, 2024.10.25	18:10:00	71.368	71.543	71.363	71.521	202	0	17, 2024.10.25	18:15:00	71.526	71.606	71.519	71.563	270	0	17, 2024.10.25	18:20:00	71.563	71.749	71.506	71.691	360	0	17, 2024.10.25	18:25:00	71.685	71.771	71.602	71.637	523	0	17, 2024.10.25	18:30:00	71.627	71.729	71.620	71.716	269	0	17, 2024.10.25	18:35:00	71.711	71.764	71.693	71.727	194	0	17, 2024.10.25	18:40:00	71.729	71.735	71.688	71.720	127	0	17, 2024.10.25	18:45:00	71.718	71.718	71.653	71.698	122	0	17, 2024.10.25	18:50:00	71.699	71.714	71.650	71.655	113	0	17, 2024.10.25	18:55:00	71.653	71.671	71.630	71.653	83	0	17, 2024.10.25	19:00:00	71.651	71.681	71.644	71.680	84	0	17, 2024.10.25	19:05:00	71.681	71.696	71.649	71.679	80	0	17, 2024.10.25	19:10:00	71.678	71.702	71.672	71.676	65	0	17, 2024.10.25	19:15:00	71.675	71.708	71.663	71.697	57	0	17, 2024.10.25	19:20:00	71.696	71.706	71.676	71.676	68	0	17, 2024.10.25	19:25:00	71.677	71.706	71.664	71.687	94	0	17, 2024.10.25	19:30:00	71.681	71.683	71.591	71.595	82	0	17, 2024.10.25	19:35:00	71.594	71.606	71.551	71.580	83	0	17, 2024.10.25	19:40:00	71.583	71.598	71.559	71.598	62	0	17, 2024.10.25	19:45:00	71.597	71.597	71.537	71.548	61	0	17, 2024.10.25	19:50:00	71.548	71.569	71.503	71.551	81	0	17, 2024.10.25	19:55:00	71.553	71.557	71.527	71.537	90	0	17, 2024.10.25	20:00:00	71.544	71.566	71.513	71.515	63	0	17, 2024.10.25	20:05:00	71.517	71.542	71.510	71.530	57	0	17, 2024.10.25	20:10:00	71.527	71.527	71.510	71.515	39	0	17, 2024.10.25	20:15:00	71.510	71.522	71.456	71.460	72	0	17, 2024.10.25	20:20:00	71.459	71.495	71.453	71.479	48	0	17, 2024.10.25	20:25:00	71.478	71.495	71.471	71.493	57	0	17, 2024.10.25	20:30:00	71.496	71.507	71.468	71.504	50	0	17, 2024.10.25	20:35:00	71.504	71.519	71.479	71.495	80	0	17, 2024.10.25	20:40:00	71.497	71.520	71.496	71.499	59	0	17, 2024.10.27	22:10:00	67.889	68.274	67.885	68.222	300	0	39, ...]

[111138 rows x 0 columns]

In [188]:
df.tail()

Empty DataFrame
Columns: []
Index: [2026.06.09	05:30:00	88.640	88.738	88.435	88.647	654	0	20, 2026.06.09	05:35:00	88.644	88.658	88.517	88.548	414	0	20, 2026.06.09	05:40:00	88.566	88.566	88.387	88.489	705	0	20, 2026.06.09	05:45:00	88.492	88.597	88.424	88.473	513	0	20, 2026.06.09	05:50:00	88.467	88.589	88.467	88.574	193	0	20]

In [189]:
df.to_csv('/Users/manton/Documents/Code/Trading/DATA/USOIL.csv')